# Aula 15 - Algoritmos e Estrutura de Dados
## Exercícios sobre Numpy

## Fácil

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [1]:
import numpy as np
print(np.__version__)

1.25.2


⚫2- Crie uma matriz 1D com números de 0 a 9

In [3]:
import numpy as np
x = np.arange(0, 10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [4]:
import numpy as np
x = np.full((3, 3), True)
print(x)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


⚫4- Extraia todos os números ímpares de de uma variável chamada ‘arr’ que recebe o vetor criado no exercício 2 acima.

In [6]:
import numpy as np
arr = np.arange(0, 10)
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)


[1 3 5 7 9]


⚫5- Substitua todos os números ímpares arr por -1

In [7]:
arr[arr % 2 == 1] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Médio

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [8]:
import numpy as np
arr = np.arange(0, 10)
arr_copy = arr.copy()
arr_copy[arr_copy % 2 == 1] = -1

print("Original array:")
print(arr)
print("Copied array with odd numbers replaced by -1:")
print(arr_copy)


Original array:
[0 1 2 3 4 5 6 7 8 9]
Copied array with odd numbers replaced by -1:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

In [9]:
import numpy as np
x = np.arange(0, 10)
x = np.reshape(x, (2, 5))

print(x)


[[0 1 2 3 4]
 [5 6 7 8 9]]


⚫3- Empilhe matrizes verticalmente:

In [ ]:
import numpy as np
x = np.arange(0, 10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)

z = np.vstack((x, y))
print(z)


⚫4- Empilhe as matrizes horizontalmente:

In [ ]:
import numpy as np
x = np.arange(0, 10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)

z = np.hstack((x, y))
print(z)


⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

In [ ]:
a = np.array([1,2,3])

In [ ]:
import numpy as np
pattern = np.hstack((a, a[::-1]))

print(pattern)


## Difícil

⚫1- Calcule as contagens de valores únicos na linha.

In [ ]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

In [ ]:
def counts_of_all_values_rowwise(arr2d):
